### ISSUE TITLE
README not updated

### ISSUE THREAD

**Issue by KKCheah** [xeggex/liquidityBot#1]
The git clone command `git clone https://github.com/xeggex/liquidityProvider` and the `cd liquidityProvider` on README are not updated as well as the "Start a Bot raw command" as well. I think the reference should change to "liquidityBot"?

**Comment by Panda777Igor** [comment]
> The git clone command `git clone https://github.com/xeggex/liquidityProvider` and the `cd liquidityProvider` on README are not updated as well as the "Start a Bot raw command" as well. I think the reference should change to "liquidityBot"?
